repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        description: "applies black formatter to .py files"
        entry: black
        language: python
        types: [python]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
      - id: check-toml
        name: Check Toml
        entry: check-toml
        types: [toml]
      - id: check-yaml
        exclude: docs/
        name: Check Yaml
        entry: check-yaml
        types: [yaml]
      - id: end-of-file-fixer
        exclude: docs/
        name: Fix End of Files
        entry: end-of-file-fixer
        types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
        exclude: docs/
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        types: [text]
        stages: [commit, push, manual]
